# server
server_name: microservice-gateway

# router
http_public_port: 
http_internal_port: 

# service

# log
log_level: debug # debug, info, warn, error, fatal, panic
log_output: stdout # stdout, file
log_file:  # log file path
log_dir:  # log file directory